INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('ESCHERICHIA COLI', 'EC');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('KLEBSIELLA PNEUMONIAE', 'KP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Enterobacter cloacae', 'ENCL');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Enterobacter agglomerans', 'ENAG');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Enterobacter species', 'ESP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Morganella morganii', 'MOM');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Proteus vulgaris', 'PRV');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('PROTEUS MIRABILIS', 'PRMI');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('PROTEUS SPECIES', 'PRSP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('CITROBACTER SPECIES', 'CITS');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Shigella species', 'SHSP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('SHIGELLA DYSENTERIAE', 'SD');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('SHIGELLA FLEXNERI', 'SF');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('SHIGELLA BOYDII', 'SB');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('SHIGELLA SONNEI', 'SS');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Salmonella species', 'SALSP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Salmonella paratyphi A', 'SALA');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Salmonella paratyphi B', 'SALB');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Salmonella paratyphi C', 'SALC');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Salmonella Typhi', 'SALD');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Vibrio cholerae', 'VC');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Vibrio species', 'VSP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Vibrio cholerae serovar. Ogawa', 'VCO');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Vibrio cholerae serovar. Inaba', 'VCI');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Serratia marcescens', 'SEMA');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('PSEUDOMONAS AERUGINOSA', 'PSAE');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('PSEUDOMONAS SPECIES', 'PSP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('STAPHYLOCCOCCUS AUREUS', 'SA');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('STAPHYLOCOCCUS SPECIES', 'SSP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('COAGULASE NEGATIVE STAPHYLOCOCCUS', 'CNS');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('GROUP A STREPTOCOCCUS (STREPTOCOCCUS PYOGENES)', 'GAS');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('GROUP B STREPTOCOCCUS (STREPTOCOCCUS AGALACTIAE)', 'GBS');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('STREPTOCOCCUS PENUMONIAE', 'STPN');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('STREPTOCOCCUS SPECIES', 'STSP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('VIRIDANS GROUP STREPTOCOCCUS', 'STVG');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('ENTEROCOCCUS SPECIES', 'ENT');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Aeromonas hydrophila', 'AH');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('HAEMOPHILUS INFLUENZAE', 'HI');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('NEISSERIA GONORRHOEAE', 'GC');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('NEISSERIA MENINGITIDIS', 'NM');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Gram-positive rods', 'GPR');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Gram-negative rods', 'GNR');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Gram-negative coccobacilli', 'GNCB');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Gram-positive cocci', 'GPC');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Gram-negative diplococci', 'GNDC');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Candida albicans', 'CANALB');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Candida species', 'CANSP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Cryptococcus neoformans', 'CRN');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Trichomonas vaginalis', 'TV');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('No Salmonella, No Shigella Isolated', 'NEGS');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('No growth after 72 hours', 'NG3');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('No growth after 24 hours', 'NG1');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('No growth after 48 hours', 'NG2');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Normal Respiratory Flora', 'NRF');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('No Pathogen Isolated', 'NPI');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('No growth after 7 days incubation', 'NG7');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('No Group A Streptococcus Isolated', 'NEGT');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Negative - No encapsulated yeast seen', 'IIN');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Positive - Encapsulated yeast seen, suggestive of Cryptococcus species', 'IIP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Negative - No evidence of Bacterial vaginosis seen', 'BVN');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Intermediate - Gram smear shows altered vaginal flora NOT consistent with bacterial vaginosis', 'BVI');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Positive - Gram smear shows altered vaginal flora consistent with bacterial vaginosis', 'BVP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Negative - No Trichomas vaginalis seen', 'TVN');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('Spermatozoa seen', 'SPRP');
INSERT INTO `blis_301`.`abbreviations` (`word`, `abbreviation`) VALUES ('No spermatozoa see', 'SPRN');
